# config/parameters.py
# Unified parameter list for both Residential and Commercial facade tenders.
# Covers all 4 categories from the Tender Summary Excel files:
#   1. Technical Specification
#   2. Tender Drawing Requirements
#   3. BOQ & Hardware
#   4. Commercial Terms & Conditions

FACADE_PARAMETERS = [

    # ══════════════════════════════════════════════════════════════
    # GROUP 1 — TECHNICAL SPECIFICATION
    # ══════════════════════════════════════════════════════════════

    {
        'name': 'wind_load',
        'display_name': 'Wind Load',
        'description': 'Design wind pressure or wind load on facade including basic wind speed, design pressure, wind zone, terrain category, and referenced standard (IS 875, ASCE 7, EN 1991-1-4)',
        'expected_units': ['kN/m²', 'Pa', 'kPa', 'm/s', 'km/h', 'psf'],
        'value_type': 'text',
        'search_keywords': ['wind load', 'wind pressure', 'design wind', 'wind force', 'basic wind speed', 'wind zone', 'terrain category', 'IS 875', 'ASCE 7', 'EN 1991'],
    },
    {
        'name': 'wind_load_zoning',
        'display_name': 'Wind Load Zoning',
        'description': 'Wind load zoning applied across the building facade — zones, corner multipliers, pressure coefficients by area',
        'expected_units': ['zone', 'kN/m²', 'Pa', 'dimensionless'],
        'value_type': 'text',
        'search_keywords': ['wind load zoning', 'wind zone', 'pressure zone', 'corner zone', 'edge zone', 'wind pressure coefficient', 'Cpe', 'Cpi'],
    },
    {
        'name': 'glass_thickness_vision_spandrel',
        'display_name': 'Glass Thickness (Vision & Spandrel)',
        'description': 'Glass specification for fixed vision and spandrel panels including thickness, makeup (e.g. 8+16+8 IGU), glass type, and coating',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['vision glass', 'spandrel glass', 'fixed glass thickness', 'glass makeup', 'IGU', 'insulating glass unit', 'double glazed', 'glass specification', 'glass build-up'],
    },
    {
        'name': 'glass_thickness_openable',
        'display_name': 'Glass Thickness (Openable)',
        'description': 'Glass specification for openable/operable panels including thickness, makeup, glass type (toughened, laminated), and coating',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['openable glass', 'opening panel glass', 'casement glass', 'operable glazing', 'vent glass', 'opening light glass', 'glazing thickness openable'],
    },
    {
        'name': 'panel_modulation',
        'display_name': 'Panel Modulation',
        'description': 'Typical panel size or grid modulation of the facade system (width × height)',
        'expected_units': ['mm', 'm', 'mm x mm', 'm x m'],
        'value_type': 'text',
        'search_keywords': ['panel modulation', 'panel size', 'grid spacing', 'bay spacing', 'module width', 'module height', 'facade grid', 'typical panel'],
    },
    {
        'name': 'bmu_load',
        'display_name': 'BMU Load',
        'description': 'Building Maintenance Unit load on facade or roof anchorage points including cradle load, gondola load, and fixing capacity',
        'expected_units': ['kN', 'kN/m', 'kg'],
        'value_type': 'text',
        'search_keywords': ['BMU', 'building maintenance unit', 'cradle load', 'gondola load', 'facade access', 'maintenance unit load', 'window cleaning', 'davit', 'monorail'],
    },
    {
        'name': 'lighting_provision',
        'display_name': 'Lighting Provision',
        'description': 'Whether lighting integration is required within the facade including LED strips, facade lighting, fin lighting, and associated loads',
        'expected_units': ['yes/no', 'W/m', 'W'],
        'value_type': 'text',
        'search_keywords': ['lighting provision', 'facade lighting', 'integrated lighting', 'LED', 'lighting load', 'fin lighting', 'illumination', 'light fitting'],
    },
    {
        'name': 'panel_typologies',
        'display_name': 'Panel Typologies',
        'description': 'Number and types of facade panel typologies (e.g. typical, corner, refuge, starter, non-typical)',
        'expected_units': ['nos', 'types'],
        'value_type': 'text',
        'search_keywords': ['panel typology', 'panel types', 'facade types', 'typical panel', 'corner panel', 'refuge panel', 'starter panel', 'panel variation'],
    },
    {
        'name': 'structural_member_wall_thickness',
        'display_name': 'Structural Member Wall Thickness',
        'description': 'Minimum wall thickness of aluminium mullion, transom, and structural members',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['wall thickness', 'member thickness', 'aluminium thickness', 'mullion thickness', 'transom thickness', 'profile thickness', 'extrusion thickness'],
    },
    {
        'name': 'material_of_gasket',
        'display_name': 'Material of Gasket',
        'description': 'Material specification for facade gaskets including EPDM, silicone, TPE, microwave gasket, and any performance standard',
        'expected_units': ['material type'],
        'value_type': 'text',
        'search_keywords': ['gasket material', 'EPDM gasket', 'silicone gasket', 'TPE gasket', 'microwave gasket', 'rubber gasket', 'gasket specification', 'weather seal'],
    },
    {
        'name': 'no_of_barriers',
        'display_name': 'No. of Barriers',
        'description': 'Number and type of barriers, handrails, balustrades, or guard rails required on the facade',
        'expected_units': ['nos'],
        'value_type': 'text',
        'search_keywords': ['number of barriers', 'no. of barriers', 'handrail', 'balustrade', 'guard rail', 'safety barrier', 'railing', 'parapet'],
    },
    {
        'name': 'stack_height',
        'display_name': 'Stack Height',
        'description': 'Vertical stack joint height or floor-to-floor height for the facade system',
        'expected_units': ['mm', 'm'],
        'value_type': 'text',
        'search_keywords': ['stack height', 'storey height', 'floor height', 'floor-to-floor', 'slab to slab', 'inter-floor height'],
    },
    {
        'name': 'vertical_stack_movement',
        'display_name': 'Vertical Stack Movement',
        'description': 'Allowable vertical movement in facade stack joints due to structural, thermal, or shrinkage movement',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['vertical stack movement', 'vertical movement', 'stack deflection', 'axial movement', 'slab deflection', 'differential movement'],
    },
    {
        'name': 'bracket_type',
        'display_name': 'Bracket Type',
        'description': 'Type of facade bracket or fixing — J-bracket, L-bracket, adjustable bracket, slab mounted, or embedded',
        'expected_units': ['type'],
        'value_type': 'text',
        'search_keywords': ['bracket type', 'J bracket', 'L bracket', 'fixing bracket', 'slab bracket', 'anchor bracket', 'facade bracket', 'fixing type'],
    },
    {
        'name': 'water_tightness',
        'display_name': 'Water Tightness',
        'description': 'Resistance to water penetration through facade joints including test pressure, performance class (E0–E4), and referenced standard (EN 12154/12155)',
        'expected_units': ['Pa', 'class E0', 'class E1', 'class E2', 'class E3', 'class E4'],
        'value_type': 'text',
        'search_keywords': ['water tightness', 'water resistance', 'water penetration', 'watertight', 'EN 12155', 'EN 12154', 'water test pressure', 'watertightness class'],
    },
    {
        'name': 'air_permeability',
        'display_name': 'Air Permeability',
        'description': 'Air leakage rate through facade under pressure including leakage class (A1–A4), test pressure, and referenced standard (EN 12152/12153)',
        'expected_units': ['m³/h·m²', 'class A1', 'class A2', 'class A3', 'class A4'],
        'value_type': 'text',
        'search_keywords': ['air permeability', 'air leakage', 'air infiltration', 'air tightness', 'EN 12153', 'EN 12152', 'air leakage class'],
    },
    {
        'name': 'seismic',
        'display_name': 'Seismic Performance',
        'description': 'Seismic design parameters including seismic zone, zone factor (Z), importance factor (I), response reduction factor (R), and inter-storey drift',
        'expected_units': ['mm', '%', 'g', 'zone'],
        'value_type': 'text',
        'search_keywords': ['seismic', 'earthquake', 'seismic zone', 'zone factor', 'importance factor', 'inter-storey drift', 'IS 1893', 'seismic coefficient'],
    },
    {
        'name': 'acoustic_rating',
        'display_name': 'Acoustic Rating',
        'description': 'Sound insulation performance of the facade including weighted sound reduction index (Rw), STC, OITC ratings',
        'expected_units': ['dB', 'Rw', 'STC', 'OITC'],
        'value_type': 'text',
        'search_keywords': ['acoustic', 'sound insulation', 'noise reduction', 'Rw', 'STC', 'OITC', 'sound reduction index', 'dB'],
    },
    {
        'name': 'u_value',
        'display_name': 'U-Value',
        'description': 'Thermal transmittance of the facade assembly including overall U-value (Uw), glass U-value (Ug), and frame U-value (Uf)',
        'expected_units': ['W/m²K', 'W/(m²·K)'],
        'value_type': 'text',
        'search_keywords': ['u value', 'u-value', 'thermal transmittance', 'Uw', 'Uf', 'Ug', 'thermal performance', 'heat transfer'],
    },
    {
        'name': 'signage_load',
        'display_name': 'Signage Load',
        'description': 'Load imposed by signage elements attached to or integrated into the facade',
        'expected_units': ['kN', 'kN/m²', 'kg'],
        'value_type': 'text',
        'search_keywords': ['signage load', 'sign load', 'signage weight', 'facade signage', 'external signage'],
    },
    {
        'name': 'horizontal_movement',
        'display_name': 'Horizontal Movement',
        'description': 'Allowable horizontal movement or inter-storey drift of the facade system including wind drift, seismic drift, and racking movement',
        'expected_units': ['mm', '%', 'H/xxx'],
        'value_type': 'text',
        'search_keywords': ['horizontal movement', 'inter-storey drift', 'lateral movement', 'racking movement', 'storey drift', 'H/200', 'H/300'],
    },
    {
        'name': 'face_width_of_mullion',
        'display_name': 'Face Width of Mullion',
        'description': 'Visible face width of the aluminium mullion profile',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['face width', 'mullion width', 'face width of mullion', 'visible width', 'sightline width'],
    },
    {
        'name': 'no_of_locking_points',
        'display_name': 'No. of Locking Points',
        'description': 'Number of locking points on openable windows, sliders, and doors',
        'expected_units': ['nos', 'points'],
        'value_type': 'text',
        'search_keywords': ['locking points', 'number of locks', 'multi-point lock', 'locking mechanism', 'lock count'],
    },
    {
        'name': 'sealant_bite',
        'display_name': 'Sealant Bite',
        'description': 'Structural silicone or weatherseal sealant bite dimension (contact width) on glass or panel',
        'expected_units': ['mm', 'as calculated'],
        'value_type': 'text',
        'search_keywords': ['sealant bite', 'silicone bite', 'structural silicone', 'sealant width', 'sealant contact', 'bite width'],
    },
    {
        'name': 'dead_load_sill_transom',
        'display_name': '100% Dead Load on Sill / Intermediate Transom',
        'description': 'Whether 100% of the glass dead load is carried on the sill or intermediate transom glass support',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['dead load sill', 'dead load transom', 'glass support dead load', 'sill dead load', '100% dead load', 'glass dead load'],
    },
    {
        'name': 'dead_load_glass_support_openable',
        'display_name': '100% Dead Load on Glass Support (Openable)',
        'description': 'Whether 100% of the dead load is on the glass support for openable panels',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['dead load openable', 'glass support openable', 'openable dead load', '100% dead load openable'],
    },
    {
        'name': 'distance_slab_to_mullion',
        'display_name': 'Distance – Slab to Mullion',
        'description': 'Distance from the slab edge to the face of the mullion or facade system',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['slab to mullion', 'slab edge distance', 'facade setback', 'mullion offset', 'slab face to mullion'],
    },
    {
        'name': 'load_of_canopy',
        'display_name': 'Load of Canopy',
        'description': 'Structural load imposed by canopy elements on the facade system',
        'expected_units': ['kN', 'kN/m', 'yes/no'],
        'value_type': 'text',
        'search_keywords': ['canopy load', 'load of canopy', 'canopy weight', 'canopy fixing load', 'entrance canopy'],
    },
    {
        'name': 'load_of_catwalk',
        'display_name': 'Load of Catwalk',
        'description': 'Structural load imposed by maintenance catwalk on the facade system',
        'expected_units': ['kN', 'kN/m', 'yes/no'],
        'value_type': 'text',
        'search_keywords': ['catwalk load', 'load of catwalk', 'access catwalk', 'maintenance catwalk', 'walkway load'],
    },
    {
        'name': 'inserts_required',
        'display_name': 'Inserts Required',
        'description': 'Whether structural inserts are required in the facade mullions or transoms, including make, coating, and scope',
        'expected_units': ['yes/no', 'scope'],
        'value_type': 'text',
        'search_keywords': ['inserts required', 'structural insert', 'mullion insert', 'steel insert', 'insert coating', 'insert scope'],
    },
    {
        'name': 'movement_slab_bracket',
        'display_name': 'Movement of Slab Mounted Bracket',
        'description': 'Allowable movement range of slab-mounted facade brackets (in-out, up-down, side)',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['slab mounted bracket', 'bracket movement', 'adjustable bracket', 'bracket adjustment range', 'fixing bracket movement'],
    },
    {
        'name': 'location_restrain_pin',
        'display_name': 'Location of Restrain Pin',
        'description': 'Location of the restrain pin within the facade — in the mullion or in the transom',
        'expected_units': ['mullion', 'transom'],
        'value_type': 'text',
        'search_keywords': ['restrain pin', 'restraint pin', 'restraint location', 'pin location', 'structural restraint'],
    },
    {
        'name': 'gutter_sleeve',
        'display_name': 'Gutter Sleeve Length & Thickness',
        'description': 'Length and thickness of gutter sleeve used in the facade system',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['gutter sleeve', 'sleeve length', 'gutter thickness', 'drainage sleeve'],
    },
    {
        'name': 'openable_edge_guard',
        'display_name': 'Openable Edge Guard – First Barrier Gasket',
        'description': 'Whether openable panel edge guard with first barrier gasket is required',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['edge guard', 'openable edge guard', 'first barrier gasket', 'barrier gasket', 'edge seal'],
    },
    {
        'name': 'drip_bar_edge_guard',
        'display_name': 'Drip Bar Edge Guard for Openable',
        'description': 'Drip bar or edge guard material and specification for openable panels',
        'expected_units': ['material', 'yes/no'],
        'value_type': 'text',
        'search_keywords': ['drip bar', 'drip edge', 'edge guard openable', 'drip moulding'],
    },
    {
        'name': 'structural_adequacy_open',
        'display_name': 'Structural Adequacy in Open Condition',
        'description': 'Whether structural adequacy in the open condition is required for openable windows or panels',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['structural adequacy', 'open condition', 'open position structural', 'wind load open'],
    },
    {
        'name': 'deflection_criteria',
        'display_name': 'Deflection Criteria',
        'description': 'Allowable deflection limits for facade members under wind load (e.g. L/175, L/200)',
        'expected_units': ['L/150', 'L/175', 'L/200', 'L/250', 'mm'],
        'value_type': 'text',
        'search_keywords': ['deflection limit', 'deflection criteria', 'allowable deflection', 'L/175', 'L/200', 'L/150', 'span deflection', 'mullion deflection'],
    },
    {
        'name': 'fire_rating',
        'display_name': 'Fire Rating',
        'description': 'Fire resistance or fire spread performance requirement including integrity (E), insulation (I) class, and duration in minutes',
        'expected_units': ['minutes', 'EI 60', 'EI 90', 'EI 120', 'E 30', 'E 60'],
        'value_type': 'text',
        'search_keywords': ['fire rating', 'fire resistance', 'fire performance', 'EI 60', 'EI 90', 'fire class', 'EN 13501', 'BS 476', 'IS 3809'],
    },
    {
        'name': 'testing_standards',
        'display_name': 'Testing Standards (Onsite / Offsite)',
        'description': 'Testing and mock-up requirements including onsite and offsite testing, standards, and test panel requirements',
        'expected_units': ['standard', 'yes/no'],
        'value_type': 'text',
        'search_keywords': ['testing standards', 'mock-up', 'prototype test', 'field test', 'laboratory test', 'onsite test', 'offsite test', 'AAMA 501', 'CWCT'],
    },
    {
        'name': 'surface_finish',
        'display_name': 'Surface Finish',
        'description': 'Coating or surface finish specification for aluminium profiles including powder coating, anodising, PVDF, AAMA grade (2603/2604/2605), and colour',
        'expected_units': ['AAMA 2603', 'AAMA 2604', 'AAMA 2605', 'microns', 'µm'],
        'value_type': 'text',
        'search_keywords': ['surface finish', 'coating', 'powder coating', 'anodising', 'PVDF', 'AAMA 2603', 'AAMA 2604', 'AAMA 2605', 'colour', 'finish specification'],
    },
    {
        'name': 'corrosion_class',
        'display_name': 'Corrosion Class for Fittings',
        'description': 'Corrosion resistance class required for hardware fittings and fasteners',
        'expected_units': ['class', 'C1', 'C2', 'C3', 'C4', 'C5'],
        'value_type': 'text',
        'search_keywords': ['corrosion class', 'corrosion resistance', 'corrosion protection', 'EN 1670', 'galvanic protection', 'marine grade'],
    },
    {
        'name': 'durability_test',
        'display_name': 'Durability Test',
        'description': 'Durability testing requirements for hardware, coatings, and facade components',
        'expected_units': ['cycles', 'standard'],
        'value_type': 'text',
        'search_keywords': ['durability test', 'durability requirement', 'cycling test', 'fatigue test', 'endurance test', 'operating cycles'],
    },
    {
        'name': 'live_load_railing',
        'display_name': 'Live Load Criteria for Railing',
        'description': 'Live load criteria for railings, balustrades, and handrails on the facade or balcony',
        'expected_units': ['kN/m', 'kN', 'kN/m²'],
        'value_type': 'text',
        'search_keywords': ['live load railing', 'railing load', 'balustrade load', 'handrail load', 'guard rail load'],
    },
    {
        'name': 'operating_force',
        'display_name': 'Operating Force Requirement',
        'description': 'Maximum force required to disengage and slide or operate windows, sliders, and doors',
        'expected_units': ['N', 'kg'],
        'value_type': 'text',
        'search_keywords': ['operating force', 'disengaging force', 'sliding force', 'opening force', 'handle force'],
    },
    {
        'name': 'easy_clean_system',
        'display_name': 'Easy Clean System in Openable',
        'description': 'Whether easy-clean or tilt-for-clean system is required in openable windows',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['easy clean', 'tilt clean', 'cleaning system', 'easy-clean mechanism'],
    },
    {
        'name': 'limiting_stay',
        'display_name': 'Limiting Stay in Openable',
        'description': 'Whether a limiting stay (restrictor) is required in openable windows for child safety or ventilation control',
        'expected_units': ['yes/no', 'mm'],
        'value_type': 'text',
        'search_keywords': ['limiting stay', 'restrictor', 'window restrictor', 'opening restrictor', 'child safety restrictor'],
    },
    {
        'name': 'door_closure_required',
        'display_name': 'Door Closure Required',
        'description': 'Whether concealed or surface-mounted door closers are required on doors',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['door closure', 'door closer', 'concealed closer', 'overhead closer', 'door closing device'],
    },
    {
        'name': 'ss_screws_visible',
        'display_name': 'SS Screws & Hardware – Visible Area',
        'description': 'Grade of stainless steel required for screws and hardware in visible areas (SS 304 or SS 316)',
        'expected_units': ['SS 304', 'SS 316'],
        'value_type': 'text',
        'search_keywords': ['stainless steel screws visible', 'SS 316 visible', 'SS 304 visible', 'hardware visible area', 'exposed fasteners'],
    },
    {
        'name': 'ss_screws_non_visible',
        'display_name': 'SS Screws & Hardware – Non-Visible Area',
        'description': 'Grade of stainless steel required for screws and hardware in non-visible or concealed areas (SS 304 or SS 316)',
        'expected_units': ['SS 304', 'SS 316'],
        'value_type': 'text',
        'search_keywords': ['stainless steel screws non-visible', 'SS 316 concealed', 'SS 304 concealed', 'hardware non-visible', 'concealed fasteners'],
    },
    {
        'name': 'aluminium_alloy',
        'display_name': 'Aluminium Alloy (6063 / 6060)',
        'description': 'Aluminium alloy specification for extrusions — 6063 or 6060 series',
        'expected_units': ['6063', '6060', 'T5', 'T6'],
        'value_type': 'text',
        'search_keywords': ['aluminium alloy', '6063', '6060', 'alloy specification', 'extrusion alloy', 'T5', 'T6'],
    },
    {
        'name': 'shims',
        'display_name': 'Shims – Make / Type (HDG / PVC)',
        'description': 'Shim material and type used in facade installation — hot dip galvanised (HDG), GI, or PVC',
        'expected_units': ['HDG', 'GI', 'PVC'],
        'value_type': 'text',
        'search_keywords': ['shims', 'shim type', 'HDG shims', 'PVC shims', 'GI shims', 'levelling shims', 'packing shims'],
    },
    {
        'name': 'pmu_requirement',
        'display_name': 'PMU Requirement',
        'description': 'Performance Mock-Up (PMU) requirements including size, test sequence, and location',
        'expected_units': ['yes/no', 'size'],
        'value_type': 'text',
        'search_keywords': ['PMU', 'performance mock-up', 'mock up requirement', 'PMU size', 'prototype mock-up', 'PMU test'],
    },
    {
        'name': 'vmu_requirement',
        'display_name': 'VMU Requirement',
        'description': 'Visual Mock-Up (VMU) requirements including size, finish samples, and review process',
        'expected_units': ['yes/no', 'size'],
        'value_type': 'text',
        'search_keywords': ['VMU', 'visual mock-up', 'visual mockup', 'VMU requirement', 'sample board', 'visual sample'],
    },

    # ══════════════════════════════════════════════════════════════
    # GROUP 2 — TENDER DRAWING REQUIREMENTS
    # ══════════════════════════════════════════════════════════════

    {
        'name': 'drawing_elevations',
        'display_name': 'Drawing – Elevations',
        'description': 'Whether facade elevation drawings are provided in the tender set',
        'expected_units': ['yes/no', 'sheets'],
        'value_type': 'text',
        'search_keywords': ['elevation drawing', 'facade elevation', 'external elevation', 'elevation sheet'],
    },
    {
        'name': 'drawing_plan',
        'display_name': 'Drawing – Plan',
        'description': 'Whether plan drawings are provided in the tender set',
        'expected_units': ['yes/no', 'sheets'],
        'value_type': 'text',
        'search_keywords': ['plan drawing', 'floor plan', 'facade plan', 'plan view'],
    },
    {
        'name': 'drawing_section',
        'display_name': 'Drawing – Section',
        'description': 'Whether section drawings (horizontal and vertical) are provided in the tender set',
        'expected_units': ['yes/no', 'sheets'],
        'value_type': 'text',
        'search_keywords': ['section drawing', 'cross section', 'vertical section', 'horizontal section', 'facade section'],
    },
    {
        'name': 'drawing_pe_typical',
        'display_name': 'Drawing – PE at Typical / Corner / Terrace / Starter',
        'description': 'Whether panel elevation (PE) drawings for typical, corner, terrace, and starter areas are provided',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['PE typical', 'panel elevation typical', 'corner PE', 'terrace PE', 'starter area PE', 'panel elevation corner'],
    },
    {
        'name': 'drawing_pe_refuge',
        'display_name': 'Drawing – PE at Refuge Area',
        'description': 'Whether panel elevation drawings for refuge floor areas are provided',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['PE refuge', 'refuge area', 'refuge floor elevation', 'panel elevation refuge'],
    },
    {
        'name': 'drawing_railing_interface',
        'display_name': 'Drawing – Railing Interface',
        'description': 'Whether railing interface details are shown in the tender drawings',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['railing interface', 'balustrade interface', 'handrail interface', 'railing connection detail'],
    },
    {
        'name': 'drawing_pe_non_typical',
        'display_name': 'Drawing – PE for Non-Typical Area',
        'description': 'Whether panel elevation drawings for non-typical facade areas are provided',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['PE non-typical', 'non typical area', 'special area elevation', 'non standard panel'],
    },
    {
        'name': 'fin_details',
        'display_name': 'Fin Details (Width, Depth, Shape)',
        'description': 'Details of facade fins including width, depth, profile shape, and location in drawings',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['fin details', 'fin width', 'fin depth', 'fin shape', 'vertical fin', 'horizontal fin', 'solar fin', 'decorative fin'],
    },
    {
        'name': 'openable_location_elevation_plan',
        'display_name': 'Location of Openable in Elevation & Plan',
        'description': 'Whether the location of openable windows is clearly shown in elevation and plan with sizes',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['openable location', 'window location elevation', 'openable in plan', 'window position elevation', 'vent location'],
    },
    {
        'name': 'coping_details',
        'display_name': 'Coping Details',
        'description': 'Details of facade coping at parapet or top of wall including material, fixing, and weathering',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['coping details', 'parapet coping', 'coping profile', 'top coping', 'wall coping'],
    },
    {
        'name': 'corner_details',
        'display_name': 'Inner / Outer Corner Details (Split / Single)',
        'description': 'Details for inner and outer corner conditions — split mullion or single profile',
        'expected_units': ['split', 'single'],
        'value_type': 'text',
        'search_keywords': ['corner details', 'inner corner', 'outer corner', 'split mullion corner', 'single mullion corner', 'corner junction'],
    },
    {
        'name': 'variable_angle',
        'display_name': 'Variable Angle',
        'description': 'Variable angle condition in facade — angled panels, non-orthogonal grids, or sloped surfaces',
        'expected_units': ['degrees', 'yes/no'],
        'value_type': 'text',
        'search_keywords': ['variable angle', 'angled facade', 'non-orthogonal', 'sloped facade', 'angle mullion'],
    },
    {
        'name': 'variable_gasket',
        'display_name': 'Variable Gasket',
        'description': 'Variable gasket or pressure plate requirements for non-standard angles or panel sizes',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['variable gasket', 'special gasket', 'custom gasket', 'non-standard gasket'],
    },
    {
        'name': 'variable_angle_mullion_semi_unitised',
        'display_name': 'Variable Angle Mullion (Semi-Unitised)',
        'description': 'Variable angle mullion condition in a semi-unitised facade system',
        'expected_units': ['yes/no', 'degrees'],
        'value_type': 'text',
        'search_keywords': ['variable angle mullion', 'semi unitised angle', 'angled semi-unitised', 'variable mullion angle'],
    },
    {
        'name': 'top_bottom_flashing',
        'display_name': 'Top & Bottom Flashing with Insulation',
        'description': 'Top and bottom flashing details — proper closure and filled with insulation',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['top flashing', 'bottom flashing', 'flashing insulation', 'head flashing', 'sill flashing', 'closure piece'],
    },
    {
        'name': 'semi_unitised_glass_support',
        'display_name': 'Semi-Unitised Glass Support and Cleats',
        'description': 'Glass support and cleat details in a semi-unitised facade system',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['semi unitised glass support', 'glass cleat', 'glass support cleat', 'semi-unitised cleat'],
    },
    {
        'name': 'gasket_transom_mullion',
        'display_name': 'Gasket for Transom and Mullion',
        'description': 'Gasket details at the interface between transom and mullion profiles',
        'expected_units': ['material', 'yes/no'],
        'value_type': 'text',
        'search_keywords': ['transom gasket', 'mullion gasket', 'transom mullion interface gasket', 'weather gasket'],
    },
    {
        'name': 'intermediate_transom_edge_guard',
        'display_name': 'Intermediate Transom Edge Guard (No Visible Screws)',
        'description': 'Intermediate transom edge guard detail with concealed/no visible screws',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['intermediate transom', 'edge guard transom', 'transom edge guard', 'concealed screw transom'],
    },
    {
        'name': 'acp_band_interface',
        'display_name': 'ACP Band Interface Details',
        'description': 'Interface details between ACP (aluminium composite panel) band and curtain wall or window system',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['ACP band', 'ACP interface', 'composite panel interface', 'ACP curtain wall junction'],
    },
    {
        'name': 'horizontal_fin_details',
        'display_name': 'Horizontal Fin Details',
        'description': 'Details of horizontal fins on the facade if applicable',
        'expected_units': ['yes/no', 'mm'],
        'value_type': 'text',
        'search_keywords': ['horizontal fin', 'sun shading fin', 'horizontal louvre fin', 'brise soleil'],
    },
    {
        'name': 'fin_lightning_provision',
        'display_name': 'Fin Lightning Provision',
        'description': 'Whether lightning protection provision is required on facade fins',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['fin lightning', 'lightning provision fin', 'lightning protection fin', 'earthing fin'],
    },
    {
        'name': 'canopy_details',
        'display_name': 'Canopy Details',
        'description': 'Details of canopy elements integrated with the facade if applicable',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['canopy details', 'entrance canopy', 'canopy design', 'canopy fixing'],
    },
    {
        'name': 'catwalk_details',
        'display_name': 'Catwalk Details',
        'description': 'Details of maintenance catwalk integrated with or attached to the facade if applicable',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['catwalk', 'maintenance walkway', 'access catwalk', 'facade catwalk'],
    },
    {
        'name': 'louvers_details',
        'display_name': 'Louvers Details (Shape & Location)',
        'description': 'Details of louvre elements on the facade — shape, depth, location in elevation, and opening percentage',
        'expected_units': ['yes/no', 'mm'],
        'value_type': 'text',
        'search_keywords': ['louvers', 'louvres', 'louvre details', 'louvre shape', 'louvre location', 'ventilation louvre'],
    },
    {
        'name': 'mullion_sleeve_length',
        'display_name': 'Mullion Sleeve Length (Semi-Unitised)',
        'description': 'Length of mullion coupling sleeve in a semi-unitised facade system',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['mullion sleeve', 'sleeve length', 'coupling sleeve', 'mullion coupling', 'semi-unitised sleeve'],
    },
    {
        'name': 'wind_load_brackets_dead_load',
        'display_name': 'Wind Load Brackets & Dead Load',
        'description': 'Wind load bracket details and dead load transfer mechanism in the facade drawings',
        'expected_units': ['yes/no', 'kN'],
        'value_type': 'text',
        'search_keywords': ['wind load bracket', 'dead load bracket', 'facade bracket wind', 'bracket dead load'],
    },
    {
        'name': 'flashings',
        'display_name': 'Flashings',
        'description': 'Flashing details at parapet, sill, head, and junction conditions in the facade drawings',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['flashing', 'flashings', 'sill flashing', 'head flashing', 'parapet flashing', 'junction flashing'],
    },
    {
        'name': 'waterproofing_membrane',
        'display_name': 'Waterproofing Membrane',
        'description': 'Waterproofing membrane details at slab edge, balcony, and junction conditions',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['waterproofing membrane', 'waterproof membrane', 'WP membrane', 'slab waterproofing', 'balcony waterproofing'],
    },
    {
        'name': 'subframes',
        'display_name': 'Subframes',
        'description': 'Subframe requirements for window and door openings including structural adequacy and performance requirements',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['subframe', 'sub frame', 'window subframe', 'door subframe', 'subframe requirement', 'structural subframe'],
    },
    {
        'name': 'perimeter_tubes',
        'display_name': 'Perimeter Tubes (Curtain Wall / Toggle / UCW)',
        'description': 'Perimeter rectangular tube details around windows and doors in curtain wall, toggle system, and UCW facades',
        'expected_units': ['yes/no', 'mm'],
        'value_type': 'text',
        'search_keywords': ['perimeter tube', 'perimeter rectangular tube', 'toggle system tube', 'UCW perimeter', 'curtain wall perimeter tube'],
    },
    {
        'name': 'fin_bracket_bolts',
        'display_name': 'Fin Bracket & Bolts',
        'description': 'Fin bracket details including bolt specifications and fixing arrangement',
        'expected_units': ['yes/no', 'M-size'],
        'value_type': 'text',
        'search_keywords': ['fin bracket', 'fin bolt', 'bracket bolt', 'fin fixing bracket', 'fin anchor'],
    },
    {
        'name': 'mullion_structural_design',
        'display_name': 'Mullion Structural Design Principle',
        'description': 'Structural design principle for the mullion — single box, double box, or other cross-section arrangement',
        'expected_units': ['double box', 'single box', 'type'],
        'value_type': 'text',
        'search_keywords': ['mullion structural design', 'mullion design principle', 'double box mullion', 'single box mullion', 'mullion cross section'],
    },
    {
        'name': 'slider_types',
        'display_name': 'Slider Types',
        'description': 'Type of sliding windows/doors required — Normal, Lift & Slide, Panorama, PD, Fold & Slide',
        'expected_units': ['type'],
        'value_type': 'text',
        'search_keywords': ['slider type', 'lift and slide', 'panorama slider', 'fold and slide', 'sliding window type', 'PD slider'],
    },
    {
        'name': 'openable_types',
        'display_name': 'Openable Types',
        'description': 'Types of openable windows required — Side Hung, Top Hung, Tilt & Turn, Bottom Hung, Double Openable, Pivot, Tilt & Slide',
        'expected_units': ['type'],
        'value_type': 'text',
        'search_keywords': ['side hung', 'top hung', 'tilt and turn', 'bottom hung', 'double openable', 'horizontal pivot', 'vertical pivot', 'tilt and slide', 'openable type'],
    },
    {
        'name': 'chajja_details',
        'display_name': 'Chajja Details (Width, Depth, Shape)',
        'description': 'Details of chajja (sun shade/projection) elements — width, depth, and profile shape',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['chajja', 'sun shade', 'projection', 'chajja width', 'chajja depth', 'chajja shape'],
    },
    {
        'name': 'no_of_floors',
        'display_name': 'No. of Floors',
        'description': 'Total number of floors in the building relevant to the facade scope',
        'expected_units': ['floors', 'nos'],
        'value_type': 'text',
        'search_keywords': ['number of floors', 'no of floors', 'total floors', 'floor count', 'storey count', 'building height floors'],
    },
    {
        'name': 'gutter_type',
        'display_name': 'Gutter – Integrated / Third Party',
        'description': 'Whether the gutter system is integrated into the facade system or supplied by a third party',
        'expected_units': ['integrated', 'third party'],
        'value_type': 'text',
        'search_keywords': ['gutter integrated', 'third party gutter', 'gutter system', 'drainage gutter', 'facade gutter'],
    },

    # ══════════════════════════════════════════════════════════════
    # GROUP 3 — BOQ & HARDWARE
    # ══════════════════════════════════════════════════════════════

    {
        'name': 'glazing_facade_area',
        'display_name': 'Glazing / Façade Area',
        'description': 'Total glazing or facade area in square metres as stated in the BOQ',
        'expected_units': ['m²', 'sqm', 'sqft'],
        'value_type': 'text',
        'search_keywords': ['glazing area', 'facade area', 'curtain wall area', 'total area', 'window area', 'BOQ area'],
    },
    {
        'name': 'handle_for_openable',
        'display_name': 'Handle for Openable',
        'description': 'Handle type and specification for openable windows — offset handle, straight handle, espagnolette handle',
        'expected_units': ['type'],
        'value_type': 'text',
        'search_keywords': ['handle openable', 'window handle', 'offset handle', 'straight handle', 'espagnolette', 'tilt and turn handle'],
    },
    {
        'name': 'handle_lockable',
        'display_name': 'Handle Requirements (Lockable / Non-Lockable / Custodian)',
        'description': 'Whether handles need to be lockable, non-lockable, or custodian key operated',
        'expected_units': ['lockable', 'non-lockable', 'custodian'],
        'value_type': 'text',
        'search_keywords': ['lockable handle', 'non-lockable handle', 'custodian handle', 'key lockable', 'restricted handle'],
    },
    {
        'name': 'outside_pull_handle',
        'display_name': 'Outside Pull Handle Required',
        'description': 'Whether outside pull handles are required on openable windows or doors',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['outside pull handle', 'external handle', 'outside handle', 'pull handle'],
    },
    {
        'name': 'hardware_specification',
        'display_name': 'Hardware Specification',
        'description': 'Hardware specification for windows and doors including brand, grade, and material requirements',
        'expected_units': ['brand', 'grade'],
        'value_type': 'text',
        'search_keywords': ['hardware specification', 'hardware brand', 'hardware grade', 'fitting specification', 'hardware make'],
    },
    {
        'name': 'threshold_type',
        'display_name': 'Door Threshold Type',
        'description': 'Door threshold type — frame threshold, medium threshold, flat/low threshold, or no threshold',
        'expected_units': ['frame', 'medium', 'flat', 'none'],
        'value_type': 'text',
        'search_keywords': ['door threshold', 'threshold type', 'flat threshold', 'low threshold', 'no threshold', 'frame threshold'],
    },
    {
        'name': 'concealed_door_closure_hinge',
        'display_name': 'Concealed Door Closure & Hinge',
        'description': 'Whether concealed door closers and concealed hinges are required on doors',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['concealed closure', 'concealed hinge', 'concealed door closer', 'hidden hinge', 'concealed hardware'],
    },
    {
        'name': 'glass_edge_to_support',
        'display_name': 'Distance – Glass Edge to Glass Support',
        'description': 'Required distance between the glass edge and the glass support (setting block or structural support)',
        'expected_units': ['mm'],
        'value_type': 'text',
        'search_keywords': ['glass edge to support', 'glass edge distance', 'setting block distance', 'glass bite', 'glass support edge'],
    },
    {
        'name': 'durability_requirements',
        'display_name': 'Durability Requirements',
        'description': 'Durability requirements for facade components and hardware including cycle counts, UV resistance, and weathering tests',
        'expected_units': ['cycles', 'years', 'standard'],
        'value_type': 'text',
        'search_keywords': ['durability requirements', 'service life', 'component durability', 'UV resistance', 'weathering test'],
    },
    {
        'name': 'lifting_provision',
        'display_name': 'Lifting Provision',
        'description': 'Whether lifting lugs, crane hooks, or vacuum lifting provisions are required on facade panels',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['lifting provision', 'lifting lug', 'vacuum lifting', 'crane hook', 'panel lifting'],
    },
    {
        'name': 'silicon_gasket',
        'display_name': 'Silicon Gasket',
        'description': 'Silicone gasket specification for facade weathersealing and structural glazing',
        'expected_units': ['type', 'colour'],
        'value_type': 'text',
        'search_keywords': ['silicone gasket', 'silicon gasket', 'structural silicone', 'weatherseal silicone', 'silicone specification'],
    },
    {
        'name': 'coating_specification',
        'display_name': 'Coating Specification (AAMA 2603 / 2604 / 2605)',
        'description': 'Powder coating or PVDF coating specification — AAMA 2603, 2604, or 2605 grade, colour, and DFT',
        'expected_units': ['AAMA 2603', 'AAMA 2604', 'AAMA 2605', 'microns'],
        'value_type': 'text',
        'search_keywords': ['AAMA 2603', 'AAMA 2604', 'AAMA 2605', 'powder coating', 'PVDF coating', 'coating grade', 'DFT', 'coating specification'],
    },
    {
        'name': 'warranty_terms',
        'display_name': 'Warranty Terms',
        'description': 'Warranty terms for the facade system including product warranty, system warranty, coating warranty, and glass warranty duration',
        'expected_units': ['years'],
        'value_type': 'text',
        'search_keywords': ['warranty terms', 'product warranty', 'system warranty', 'coating warranty', 'glass warranty', 'warranty period', 'guarantee terms'],
    },
    {
        'name': 'metal_separator',
        'display_name': 'Metal Separator',
        'description': 'Whether metal separators or thermal breaks are required between aluminium profiles and concrete/steel structure',
        'expected_units': ['yes/no', 'type'],
        'value_type': 'text',
        'search_keywords': ['metal separator', 'thermal break', 'isolation strip', 'separator plate', 'bi-metallic isolation'],
    },
    {
        'name': 'perimeter_rectangular_tube',
        'display_name': 'Perimeter Rectangular Tube',
        'description': 'Perimeter rectangular hollow section tube specification for facade framing',
        'expected_units': ['mm x mm', 'mm'],
        'value_type': 'text',
        'search_keywords': ['perimeter tube', 'rectangular tube', 'RHS tube', 'hollow section perimeter', 'box section perimeter'],
    },
    {
        'name': 'fasteners',
        'display_name': 'Fasteners',
        'description': 'Fastener specification for facade assembly including self-drilling screws, rivets, bolts, and grade',
        'expected_units': ['grade', 'size', 'type'],
        'value_type': 'text',
        'search_keywords': ['fasteners', 'screws', 'self-drilling screw', 'rivet', 'bolt specification', 'fastener grade'],
    },
    {
        'name': 'screw_hole_caps',
        'display_name': 'Screw Hole Caps',
        'description': 'Whether screw hole caps or plugs are required on visible screw heads',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['screw hole caps', 'screw cap', 'screw plug', 'hole cover', 'cap plug'],
    },
    {
        'name': 'fin_end_caps',
        'display_name': 'Fin End Caps',
        'description': 'End cap specification for facade fins including material and fixing method',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['fin end cap', 'end cap', 'fin closure', 'profile end cap'],
    },
    {
        'name': 'handle_for_sliders',
        'display_name': 'Handle for Sliders',
        'description': 'Handle type for sliding windows/doors — retaining catch or lever handle',
        'expected_units': ['retaining catch', 'lever handle'],
        'value_type': 'text',
        'search_keywords': ['slider handle', 'sliding handle', 'retaining catch', 'lever handle slider', 'handle for slider'],
    },
    {
        'name': 'lock_key_required',
        'display_name': 'Lock & Key Required',
        'description': 'Whether lock and key is required for openable windows, sliders, and doors',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['lock and key', 'key lock', 'locking mechanism', 'window lock', 'door lock', 'key operated'],
    },
    {
        'name': 'standard_custom_colour',
        'display_name': 'Standard / Custom Colour',
        'description': 'Whether standard RAL colour or custom colour is required for the facade coating',
        'expected_units': ['standard', 'custom', 'RAL'],
        'value_type': 'text',
        'search_keywords': ['standard colour', 'custom colour', 'RAL colour', 'special colour', 'colour selection', 'bespoke colour'],
    },
    {
        'name': 'track_protection',
        'display_name': 'Track Protection',
        'description': 'Whether track protection covers or pads are required for sliding window/door tracks',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['track protection', 'track cover', 'sliding track protection', 'track guard'],
    },
    {
        'name': 'ventilator_type',
        'display_name': 'Ventilator Type (Exhaust Fan / Louvre)',
        'description': 'Type of ventilator integrated into the facade — exhaust fan or louvre ventilator',
        'expected_units': ['exhaust fan', 'louvre'],
        'value_type': 'text',
        'search_keywords': ['ventilator type', 'exhaust fan', 'louvre ventilator', 'ventilation type', 'facade ventilation'],
    },
    {
        'name': 'door_type',
        'display_name': 'Door Type (Pivot / Swing)',
        'description': 'Type of door — pivot door or swing (side-hung) door',
        'expected_units': ['pivot', 'swing'],
        'value_type': 'text',
        'search_keywords': ['door type', 'pivot door', 'swing door', 'side hung door', 'door configuration'],
    },
    {
        'name': 'georgian_bar',
        'display_name': 'Georgian Bar Requirements',
        'description': 'Whether Georgian bar (simulated divided lite) grilles are required in glazing',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['Georgian bar', 'glazing bar', 'grille bar', 'simulated divided lite', 'SDL'],
    },
    {
        'name': 'integration_ventilators',
        'display_name': 'Integration with Ventilators (Renson)',
        'description': 'Whether integration with specialist ventilators (e.g. Renson brand) is required',
        'expected_units': ['yes/no', 'brand'],
        'value_type': 'text',
        'search_keywords': ['Renson', 'ventilator integration', 'specialist ventilator', 'facade ventilator brand'],
    },
    {
        'name': 'interlock_end_caps',
        'display_name': 'Interlock End Caps',
        'description': 'End cap specification at slider or panel interlocks',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['interlock end cap', 'slider interlock cap', 'panel interlock cap'],
    },
    {
        'name': 'door_stopper',
        'display_name': 'Door Stopper',
        'description': 'Whether door stoppers are required on doors — floor mounted, wall mounted, or magnetic',
        'expected_units': ['yes/no', 'type'],
        'value_type': 'text',
        'search_keywords': ['door stopper', 'door stop', 'floor door stop', 'wall door stop', 'magnetic door stop'],
    },
    {
        'name': 'automation',
        'display_name': 'Automation',
        'description': 'Whether window or door automation (motorised operation) is required',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['automation', 'motorised', 'automatic window', 'automated door', 'electric actuator', 'motor drive'],
    },

    # ══════════════════════════════════════════════════════════════
    # GROUP 4 — COMMERCIAL TERMS & CONDITIONS
    # ══════════════════════════════════════════════════════════════

    {
        'name': 'dlp',
        'display_name': 'DLP (Defect Liability Period)',
        'description': 'Defect liability period required after practical completion',
        'expected_units': ['months', 'years'],
        'value_type': 'text',
        'search_keywords': ['DLP', 'defect liability period', 'defects liability', 'defect notification period', 'liability period', 'maintenance period'],
    },
    {
        'name': 'bank_guarantee',
        'display_name': 'BG (Bank Guarantee)',
        'description': 'Bank guarantee percentage and period required',
        'expected_units': ['%', 'months'],
        'value_type': 'text',
        'search_keywords': ['bank guarantee', 'BG', 'performance bond', 'performance guarantee', 'advance payment guarantee'],
    },
    {
        'name': 'retention',
        'display_name': 'Retention',
        'description': 'Retention percentage held from progress payments',
        'expected_units': ['%'],
        'value_type': 'text',
        'search_keywords': ['retention', 'retention money', 'retention percentage', 'retention amount', 'held retention'],
    },
    {
        'name': 'quotation_validity',
        'display_name': 'Quotation Validity',
        'description': 'Period for which the tender quotation price is valid',
        'expected_units': ['days', 'months'],
        'value_type': 'text',
        'search_keywords': ['quotation validity', 'quote validity', 'tender validity', 'price validity', 'offer validity'],
    },
    {
        'name': 'nalco_rate',
        'display_name': 'NALCO Rate / Clause',
        'description': 'NALCO (National Aluminium Company) rate or aluminium price escalation clause applicable',
        'expected_units': ['INR/kg', 'clause'],
        'value_type': 'text',
        'search_keywords': ['NALCO rate', 'NALCO clause', 'aluminium escalation', 'metal price clause', 'NALCO price'],
    },
    {
        'name': 'rate_validity',
        'display_name': 'Rate Validity',
        'description': 'Period for which the contract rates are fixed / validity of unit rates',
        'expected_units': ['months', 'days'],
        'value_type': 'text',
        'search_keywords': ['rate validity', 'rate fixed period', 'rate escalation', 'unit rate validity'],
    },
    {
        'name': 'supplies_validity',
        'display_name': 'Supplies Validity',
        'description': 'Validity period for supply commitments and delivery schedules',
        'expected_units': ['months', 'days'],
        'value_type': 'text',
        'search_keywords': ['supplies validity', 'supply commitment', 'delivery validity', 'supply schedule validity'],
    },
    {
        'name': 'scope_of_supply',
        'display_name': 'Scope of Supply (CIF / Ex Works)',
        'description': 'Scope of supply terms — CIF (Cost, Insurance, Freight) or Ex Works (EXW)',
        'expected_units': ['CIF', 'Ex Works', 'EXW', 'DDP'],
        'value_type': 'text',
        'search_keywords': ['scope of supply', 'CIF', 'Ex Works', 'EXW', 'DDP', 'supply terms', 'incoterms'],
    },
    {
        'name': 'wastages',
        'display_name': 'Wastages',
        'description': 'Wastage allowance percentage included in the BOQ or contract',
        'expected_units': ['%'],
        'value_type': 'text',
        'search_keywords': ['wastages', 'wastage allowance', 'material wastage', 'wastage percentage', 'scrap allowance'],
    },
    {
        'name': 'project_completion_timelines',
        'display_name': 'Project Completion Timelines',
        'description': 'Project schedule and facade completion milestones',
        'expected_units': ['months', 'weeks', 'date'],
        'value_type': 'text',
        'search_keywords': ['completion timeline', 'project schedule', 'handover date', 'completion date', 'facade programme', 'construction schedule'],
    },
    {
        'name': 'project_management_requirements',
        'display_name': 'Project Management Requirements',
        'description': 'Project management requirements including site manager, QC, progress reporting, and attendance at meetings',
        'expected_units': ['text'],
        'value_type': 'text',
        'search_keywords': ['project management', 'site manager', 'QC plan', 'quality control', 'progress report', 'project coordinator'],
    },
    {
        'name': 'shop_drawings',
        'display_name': 'Shop Drawings',
        'description': 'Shop drawing submission requirements including schedule, approval process, and revisions',
        'expected_units': ['text', 'weeks'],
        'value_type': 'text',
        'search_keywords': ['shop drawings', 'fabrication drawings', 'shop drawing approval', 'GA drawings', 'detailed drawings'],
    },
    {
        'name': 'tolerances',
        'display_name': 'Tolerances',
        'description': 'Installation and fabrication tolerances for the facade system',
        'expected_units': ['mm', '±mm'],
        'value_type': 'text',
        'search_keywords': ['tolerances', 'installation tolerance', 'fabrication tolerance', 'alignment tolerance', 'setting out tolerance'],
    },
    {
        'name': 'pmu_cost',
        'display_name': 'PMU Cost',
        'description': 'Cost of Performance Mock-Up (PMU) testing and its inclusion in the contract price',
        'expected_units': ['INR', 'lump sum', 'included'],
        'value_type': 'text',
        'search_keywords': ['PMU cost', 'mock-up cost', 'testing cost', 'PMU price', 'prototype cost'],
    },
    {
        'name': 'mode_of_measurement',
        'display_name': 'Mode of Measurement (BOQ / Actual Size)',
        'description': 'How quantities are measured — BOQ sizes (nominal) or actual installed sizes',
        'expected_units': ['BOQ sizes', 'actual size'],
        'value_type': 'text',
        'search_keywords': ['mode of measurement', 'measurement method', 'BOQ size measurement', 'actual size measurement', 'quantity measurement'],
    },
    {
        'name': 'payment_terms',
        'display_name': 'Payment Terms',
        'description': 'Payment schedule and terms including advance payment, milestone payments, and final payment conditions',
        'expected_units': ['%', 'days'],
        'value_type': 'text',
        'search_keywords': ['payment terms', 'payment schedule', 'advance payment', 'milestone payment', 'progress payment', 'payment conditions'],
    },
    {
        'name': 'mtc',
        'display_name': 'MTC (Material Test Certificate)',
        'description': 'Whether Material Test Certificates (MTC) are required for aluminium, glass, and hardware',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['MTC', 'material test certificate', 'mill certificate', 'test certificate', 'material certification'],
    },
    {
        'name': 'protection_tape',
        'display_name': 'Protection Tape',
        'description': 'Whether protective tape/film is required on aluminium profiles and glass during installation',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['protection tape', 'protective tape', 'protective film', 'surface protection', 'aluminium protection tape'],
    },
    {
        'name': 'no_of_lots',
        'display_name': 'No. of Lots Required',
        'description': 'Number of construction lots or phases for facade installation',
        'expected_units': ['nos', 'lots'],
        'value_type': 'text',
        'search_keywords': ['number of lots', 'construction lots', 'installation phases', 'facade lots', 'lot requirement'],
    },
    {
        'name': 'stationed_service_engineer',
        'display_name': 'Stationed Service Engineer',
        'description': 'Whether a stationed service engineer is required on site during installation or DLP',
        'expected_units': ['yes/no', 'duration'],
        'value_type': 'text',
        'search_keywords': ['stationed service engineer', 'site engineer', 'service engineer', 'on-site engineer', 'resident engineer'],
    },
    {
        'name': 'stationed_project_manager',
        'display_name': 'Stationed Project Manager',
        'description': 'Whether a stationed project manager is required on site',
        'expected_units': ['yes/no', 'duration'],
        'value_type': 'text',
        'search_keywords': ['stationed project manager', 'site project manager', 'resident project manager', 'on-site PM'],
    },
    {
        'name': 'sample_board',
        'display_name': 'Sample Board',
        'description': 'Sample board requirements including finishes, colours, hardware, and glass samples for approval',
        'expected_units': ['yes/no'],
        'value_type': 'text',
        'search_keywords': ['sample board', 'finish sample', 'colour sample', 'hardware sample', 'glass sample', 'sample approval'],
    },
]
